### ISSUE TITLE
시작

### ISSUE THREAD

**Issue by kickscar-admin** [hanseonghye/myblog#1]
만든거 보고 내 블로그로도 써주겠음~ ㅋ~
화이팅해랏!

**Comment by kickscar-admin** [comment]
장고는 오버지게 했는데....  플라스크로 어떠냐?
그냥 딴지다!

**Comment by hanseonghye** [comment]
> 장고는 오버지게 했는데.... 플라스크로 어떠냐?
> 그냥 딴지다!

(부담부담)

**Comment by kickscar-admin** [comment]
> > 장고는 오버지게 했는데.... 플라스크로 어떠냐?
> > 그냥 딴지다!
> 
> (부담부담)

갠플젝이고 스터디 겸사겸사인데...  왠 부담부담? 똑같은 하면 왜 하냐???

'cause
1. 현업에서는 플라스크를 더 선호한다.
2. 자유도가 높아 날아갈 꺼 같을 꺼다.
3. 장고버젼 블로그는 아무리 잘해도 쌤 개발블로그에 안쓸꺼임 ㅋ;
4. 쌤이 사실 장고보다 플라스크를 더 익숙함 ^^;

플라스크책 필요하면 말해라 보던 책 드리겠뜸!!

**Comment by kickscar** [comment]
카톡하지 말고 개발이슌 여기다 해!!!! 잘 생각했음!!!

이이슈 닫는다. 
이 플젝에다 플라스크 세팅 해바바 
보고 플라스크 세팅 이슈 열어서 리뷰해줄깨

고생해라~
