### ISSUE TITLE
Verify Model

### ISSUE THREAD

**Issue by kickscar-admin** [hanseonghye/myblog#2]
모델 검증을 시작하긋다

**Comment by kickscar** [comment]
머 할 것도 없구만... ㅋ;;
카테고리는 저정도면 될 것 같고 포스트도 외래키 잡는 거 말곤 별거 없는데? (흠 잡을 게 없다공 -,.-;)

근데....  JBlog 냄새 넘 나지 않음? JBLOG 좀 벗어 나야하지 않음?

네이버 블로그뿐만 아니라 보통 멀티 카테고리 지원하쥐...
예를 들어 카테고리가 Python, Django가 있는데, MyBlog만들다 생긴 기술 내용 포스트를
두 카테고리에  동시에 올라가야 할 것 같다. 어쩔래?

음.... 고민하지 말고... 톨날 예로 보여준 애들 많이들 쓰는 그 블로그 비스무리한 거 있지?
고정도만 만들어 보쟌. 그럼 난 그거 안쓰고 니꺼 쓸 꺼 같음 ^^...  
 
태그는 하다 말았구나? 저렇게 VARCHAR로 잡아 버리면 문제있다.
1NF에 대한 정면 도전이다. 머 하다 만거라 생각하고...

고생했음!! =b

**Comment by hanseonghye** [comment]
> 머 할 것도 없구만... ㅋ;;
> 카테고리는 저정도면 될 것 같고 포스트도 외래키 잡는 거 말곤 별거 없는데? (흠 잡을 게 없다공 -,.-;)
> 
> 근데.... JBlog 냄새 넘 나지 않음? JBLOG 좀 벗어 나야하지 않음?
> 
> 네이버 블로그뿐만 아니라 보통 멀티 카테고리 지원하쥐...
> 예를 들어 카테고리가 Python, Django가 있는데, MyBlog만들다 생긴 기술 내용 포스트를
> 두 카테고리에 동시에 올라가야 할 것 같다. 어쩔래?
> 
> 음.... 고민하지 말고... 톨날 예로 보여준 애들 많이들 쓰는 그 블로그 비스무리한 거 있지?
> 고정도만 만들어 보쟌. 그럼 난 그거 안쓰고 니꺼 쓸 꺼 같음 ^^...
> 
> 태그는 하다 말았구나? 저렇게 VARCHAR로 잡아 버리면 문제있다.
> 1NF에 대한 정면 도전이다. 머 하다 만거라 생각하고...
> 
> 고생했음!! =b

멀티 카테고리 도전하겠습니담~

**Comment by kickscar** [comment]
애들 깃협에서 많이 쓰는 그 기술블로그가 머지?
나도 그거좀 보고 참고좀 해바야 겠다.
아! 이 플젝 나 콜라보하구 프라이빗으로 바꿔!
니 IDE 모냐?
